[package]
name = "payload"
version = "2.0.0"
edition = "2024"

[lib]
name = "utils"
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.62.0", features = ["Win32_UI_WindowsAndMessaging"] }
